### ISSUE TITLE
Travis: test_no_timeout_locate_ns_not_existing

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#101]
https://travis-ci.org/opensistemas-hub/osbrain/jobs/215867787

Ocurred a couple of times already. We should check it and maybe be more lenient with the time requirement.

**Comment by Flood1993** [comment]
Yes, this seems to be the most problematic test. Also in https://travis-ci.org/opensistemas-hub/osbrain/jobs/216400996

**Comment by Peque** [comment]
Hopefully fixed with c8bb10397235bb35715eeeee493e11fae20e5fdf.
