### ISSUE TITLE
Travis: test_agent_proxy_remote_exceptions

### ISSUE THREAD

**Issue by Flood1993** [opensistemas-hub/osbrain#122]
https://travis-ci.org/opensistemas-hub/osbrain/jobs/233143995

**Comment by Peque** [comment]
Again: https://travis-ci.org/opensistemas-hub/osbrain/jobs/242905748

**Comment by Peque** [comment]
This might just be a consequence of #137. I mean, the second error might just be a consequence of the first one (i.e.: the first error leaves the tester process in a bad state and results in a new error on the next test execution).

Maybe we should just concentrate on #137 and then see if we still get errors on Travis. If you agree we could just close this issue for now.

**Comment by Peque** [comment]
Probably fixed by #170.
