### ISSUE TITLE
Travis: test_agent_sync_publications_handlers.py

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#134]
Currently `test_agent_sync_publications_handlers.py` is failing very frequently. These tests failed just with today PRs:

- https://travis-ci.org/opensistemas-hub/osbrain/jobs/242481416
- https://travis-ci.org/opensistemas-hub/osbrain/jobs/242463748
- https://travis-ci.org/Peque/osbrain/jobs/242463060
- https://travis-ci.org/Peque/osbrain/jobs/242480900

**Comment by Peque** [comment]
`test_sync_pub_connect_handler_types`:

```python
# ...
server.publish()
assert wait_agent_attr(client, length=1)
# ...
```

That is risky as the client might not be connected (and receiving messages) when the publisher sends the message. If you are just checking that the client receives messages from the server, maybe you can:

```python
# ...
server.each(0.1, 'publish')
assert wait_agent_attr(client, data='publication!')
# ...
```

What you think?

**Comment by Peque** [comment]
`test_sync_pub_send_handlers`:

I think you need to make sure client-server are connected here as well. Maybe you can do just like in the test above:

- Start publishing each period.
- Wait until we make sure the client is receiving messages from the server.
- Optionally, stop the timer.

Then we can send the request and wait for the response:

```python
client.send('sub', 'request!', handler=handler)
assert wait_agent_attr(client, ...)  # Make sure we receive the expected response for the request...
```

What you think?

**Comment by Flood1993** [comment]
In relation to this: #136 

There I have fixed the issue with `test_sync_pub_connect_handler_types`. However, for `test_sync_pub_send_handlers`, I don't think it is necessary to check the client-server connection with the same method, since I think we would only be checking the connection of the PUB/SUB part. My intent with the second function was to check that the handler specified in the send call (request) is the one that will be used when we get the reply, therefore raising an exception for normal incoming messages (through the SUB socket). In other words, I wanted to `isolate` that specific check.

**Comment by Flood1993** [comment]
Failing due to this: https://travis-ci.org/opensistemas-hub/osbrain/jobs/242764194 so I will implement it there too.

**Comment by Peque** [comment]
It is hard to isolate, as the reply to the request will be sent over the PUB-SUB socket in the channel. That means we really need to make sure the connection is well established. Note that yes, we could make a request before the PUB/SUB communication is guaranteed to be established.

Alternatives in my opinion:

- Either check client-server connection with the same method as in the test above. Then make sure the handler for the request does something different than the handler for the subscription (that way you can verify the correct handler is used).
- If you think that is a lot of repetition then maybe consider merging the two tests if that makes sense.
- Or alternatively repeat the request (with a timer) until you get the reply.

I prefer the first approach, even if it feels like repeating the first test. It is not a strong opinion though, so feel free to take any other approach. :wink:
