### ISSUE TITLE
cannot import name 'run_nameserver'

### ISSUE THREAD

**Issue by ChaoYue0307** [opensistemas-hub/osbrain#145]
When I run the example code of hello world, I get the ImportError as below

Traceback (most recent call last):
  File "osbrain.py", line 1, in <module>
    from osbrain import run_nameserver
  File "/home/chaoyue/Desktop/scripts/osbrain.py", line 1, in <module>
    from osbrain import run_nameserver
ImportError: cannot import name 'run_nameserver'

What's wrong and how to fix?

**Comment by Peque** [comment]
Do you, by any chance, have a local file named `osbrain.py`? If so, that could be causing trouble, as Python will try to import `run_nameserver` from your local file (it has priority over your installed modules). Simply rename that file to something else.

**Comment by ChaoYue0307** [comment]
Exactly the naming issue! Thanks a lot for pointing out !
