### ISSUE TITLE
Proxy method to wait for agent to be running

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#153]
Either create this method (does not break anything) or change the default behavior when creating proxies to agents so that these proxies wait for the agent not only to be ready but running.

What is the best option?

Update
---------

The issue is with proxy creation, that means, when creating a `osbrain.Proxy(...)` object. It currently waits for the agent to be ready (i.e.: registered in the name server and with the Pyro4 server running). However, it does not wait for it to be running, which should probably be the default behavior.

**Comment by deeper-dot-hex** [comment]
second option seems to be better, for consistency. That is, given an AS (Agent Status), and "ready" and "running" as enumeration of its value, osbrain system logic can handle 
  
AS = ( ¬ready ∧ ¬running )  ∨ ( ready ∧ ¬running ) ∨ ( ready ∧ running ) 

Actual weakness belong to falling check of 2nd clause of equation

**Comment by Peque** [comment]
Yeah, the second option is probably the best. Historically, that was not actually the case, as the old implementation required for some agent configuration to be executed "offline" (when the agent was not running). But that is no longer required.

Anyway, maybe we could still add a parameter `running=True` for proxy creation to let the user decide whether or not they want to wait for the agent to be running or not (by default, it will wait).

@Flood1993 what do you think? Should we add a parameter? Or maybe we could go, for now, without that parameter, and add it in the future if users really need it.

**Comment by Peque** [comment]
On the other hand if the user really wanted to do something with the agent while it is not running, they could always stop it, do that thing, and then run it again. :confused: (just thinking out loud) :stuck_out_tongue_winking_eye:

**Comment by Flood1993** [comment]
I think the parameter would be a great option, and I also agree with the default option to be to wait for the agent to be running :+1:

**Comment by Peque** [comment]
@deeper-dot-hex We would like to include this for 0.6.0 release. Are you still interested in contributing/helping with this? Otherwise we will implement it ourselves. :wink:

**Comment by ocaballeror** [comment]
I don't understand. How is the proxy supposed to wait for the agent at creation time? The agent will not be running until `proxy.run()` is invoked, so I assume that method call must be done inside `__init__`.
So I figure the code should look something like this:
```python
class Proxy:
  def __init__(self):
  ...
  if run_on_startup:
    self.run()
    self.wait_to_be_running()
```

```python
def run_agent():
  ...
  proxy = Proxy(...)
  # and remove the call to proxy.run() that was previously here
```

Is that right?

**Comment by Peque** [comment]
@ocaballeror I understand your confusion there. It is not the `Proxy`'s responsibility to run the agent, that must be done within `run_agent()` or manually.

Note that you can create a proxy to an agent manually at any time, calling `proxy = Proxy('agent_alias')`. There, we should wait, by default, for the agent to be running.

Imagine we create and run an agent from one script and then try to create a proxy from another script (i.e.: for distributed systems). If we do not wait for the agent to be running, which is what the user is probably expecting, we will not be able to use the proxy normally (i.e.: calling methods remotely).

Think about this case (which you can use as a test case): you run an agent, then you stop it, but do not kill it (there is a `.stop()` method for that). Now you create a proxy. This proxy should wait, at least for some time, until the agent is running, then raise an exception. So in your test case you should expect and catch that exception.

**Comment by Peque** [comment]
@ocaballeror Related issue: #150. I think it all started there. :stuck_out_tongue_winking_eye:

**Comment by ocaballeror** [comment]
Why raise an exception? Why not just create a loop that waits for the agent to be running and only exit when it is (or raise an exception if it times out)?

**Comment by Peque** [comment]
@ocaballeror Yeah, that is what I meant: "wait, at least for some time (the timeout), until the agent is running, then (if it is not running after the timeout) raise an exception". My sentence was definitely incomplete. :joy:
