### ISSUE TITLE
Shutdown by default on examples

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#162]
Right now the initial examples do not use the `shutdown` method (it is explained later in the documentation).

Maybe we should introduce the shutdown method from the very beginning, as this way the examples can be run without the need to be interrupted with CTRL+C (they do not block forever). This might be more intuitive for beginners than having to kill all the system "by hand".

@Flood1993 what you think?

**Comment by Flood1993** [comment]
I think it would be a great addition ^^

**Comment by Flood1993** [comment]
Solved in #183
