### ISSUE TITLE
How to return an output from a handler function?

### ISSUE THREAD

**Issue by sjanko2** [opensistemas-hub/osbrain#167]
Hi there,

I may just be missing something, but is there any way to return a value from a handler function once a message is received? All of the examples I saw in the documentation used the handler function simply to print a phrase. 

I have code where one agent waits to receive "I'm Ready" signals from all other agents before sending a particular message. As such, I want to update a variable from inside the handler function every time a message is received. I have tried using global variables inside the handler function with no luck. Besides this, the only way I know how to get an output value from a function is to put it in this form:

output = function(input)

Since the handlers are set up inside the connection based on their topic, I don't see any way to specify this output....

Here is an example to illustrate what I'm saying:

```
AgentManager.connect(Agent1, handler = {'Intro': log_message, 'ImReady': tallyreadies})
```

Agent1 is set up to publish. AgentManager has connected to Agent1's publishing address. When receiving a message of the topic "ImReady", the AgentManager uses the following function:

```
def tallyreadies(agent, message):
    global ScenarioReady  
    ScenarioReady = 1*int(message)
```

I have tested this and the ScenarioReady variable does not update outside the function. I have also tried:

```
def tallyreadies(agent, message):
    ScenarioReady = 1*int(message)
    return ScenarioReady
```

I'm probably missing something obvious, but I have been stuck on it for awhile. Does anyone have any suggestions?

Thanks so much!

Sam

**Comment by Flood1993** [comment]
Hello,

Hopefully, I'm not missing anything.

The only cases in which you would want to return (or yield) something from a handler would be when that returned object is to be sent to another agent:
- After a request is received in a SYNC_PUB socket.
- After a request is received in an ASYNC_REP or a REP socket.

Since in any other case we won't be sending a message back, we do not have to return anything.

If I understood correctly, I would try something like this (supposing you know the total number of agents which will be connected to AgentManager):
- In the AgentManager, create an attribute of type `set()` (list without repeated elements).
- Set the handler for the 'ImReady' topic to a function that will add the received message to the set.
- From the sending agents, send their uuid along the 'ImReady' topic. You should send it periodically (with a `each` timer) since messages sent before the communication is stablished might be lost using the PUB/SUB pattern.
- In the AgentManager, wait until the length of the `set()` created before reaches the number of agents.

Since we are storing only unique uuid's in AgentManager and each Agent would be sending its own uuid, when both lenghts are equal it would mean

**Comment by Peque** [comment]
Hi @sjanko2,

You must realize agents, by default, are system processes. When you create one, a fork occurs and the child process gets a copy of the state of the father. This means that, if you try to modify a global variable, you will be modifying the copy on the child (Unix systems implement copy-on-write). Maybe that is why you see that "unexpected" behavior (which is totally expected). :stuck_out_tongue_winking_eye: 

If you want to keep state within the agent, you should use an attribute instead:

```python
def tallyreadies(agent, message):
    # Change the value of an attribute in the agent
    agent.scenario_ready = 1 * int(message)  
```

If you want to share state between agents, then use message passing, or take advantage of the proxies if performance is not critical.

Please, if you have other questions make sure to provide a [minimal, complete and verifiable](https://stackoverflow.com/help/mcve) example. Many times code is easier to understand than words. :wink:

**Comment by sjanko2** [comment]
Hello,

Thank you so much for the suggestions. I apologize for not including a more complete example before.

Attached I have included an example of three agents. Agent 1 acts as the "AgentManager" previously mentioned, while Agent 2 and Agent 3 are the other agents that send the "Im Ready" message to Agent 1. 

I have attempted to create an attribute of type set in Agent 1. However, I cannot figure out how to add to the set from inside the function... I think I may need more clarification on how to do that. The messages from Agent 2 and Agent 3 specify a number (Agent 2 sends "2" and Agent 3 sends "3"), so Agent 1 is waiting for a set that has 2 unique values to continue.

Please run these in order: Agent1.py, Agent2.py, then Agent3,py.

Thank you so, so much as always!! You guys are awesome. :)

Sam

---
Agent1.py
---

```
from osbrain import run_agent
from osbrain import run_nameserver
import osbrain
import time

osbrain.config['TRANSPORT'] = 'tcp'

def tallyreadies(agent, message):
    Agent1Proxy.ScenarioReady.add(message)

if __name__ == '__main__':

    # Start the nameserver:
    ns = '127.0.0.1:1124'
    nsP = run_nameserver(ns)

    # Run the Agent
    Agent1Proxy = run_agent('Agent1', ns)

    # Create address for Agent1's publishing
    Agent1PubAdderess = Agent1Proxy.bind('PUB', alias = 'PUBStream')

    # Create ScenarioReady attribute of type set()
    Agent1Proxy.ScenarioReady = set()
    print(type(Agent1Proxy.ScenarioReady))
    print(Agent1Proxy.ScenarioReady)

    # Have this agent wait until the other agents have registered:
    print('Waiting for all agents to arrive...')
    agentsinNS = osbrain.nameserver.NameServer.agents(nsP)

    while len(agentsinNS) < 3:
        agentsinNS = osbrain.nameserver.NameServer.agents(nsP)

    print('All agents have arrived!')
    print('The agents in the nameserver are: %s' %agentsinNS)

    # Create proxies to all agents and save publishing addresses
    Agent2Proxy = nsP.proxy(agentsinNS[1])
    Agent2PubAdderess = Agent2Proxy.bind('PUB', alias = 'PUBStream')

    Agent3Proxy = nsP.proxy(agentsinNS[2])
    Agent3PubAddress = Agent3Proxy.bind('PUB', alias = 'PUBStream')

    # Connect Agent 1 to all other agents
    Agent1Proxy.connect(Agent2PubAdderess, handler = {'ImReady': tallyreadies})
    Agent1Proxy.connect(Agent3PubAddress, handler = {'ImReady': tallyreadies})

    # Have Agent 1 wait until all agents have said they are ready
    while len(Agent1Proxy.ScenarioReady) < 3:
        print ('Agents are not ready yet.')
        time.sleep(3)

    # Send message to all saying we are ready to begin
    Agent1Proxy.send('PUBStream', 'All agents are ready! We will now begin.', topic = 'Intro')
```

---
Agent2.py
---

```
from osbrain import run_agent
from osbrain import run_nameserver
import osbrain
from osbrain.proxy import NSProxy, locate_ns
import time

osbrain.config['TRANSPORT'] = 'tcp'

def log_message(agent, message):
    agent.log_info('Received: %s' % message)

if __name__ == '__main__':

    # Get nameserver proxy
    ns = '127.0.0.1:1124'
    nsaddr = locate_ns(ns)
    nsP = NSProxy(nsaddr)

    # Run the Agent
    print('Registering Agent 2 with the server...')
    Agent2Proxy = run_agent('Agent2', nsaddr)
    print('Agent registered!')
    time.sleep(3)

    # Create proxy to Agent 1 and connect to receive Intro message
    Agent1Proxy = nsP.proxy('Agent1')

    # Wait for proxy to set up
    checkstatus = Agent1Proxy.get_attr('running')

    while checkstatus == False:
        checkstatus = Agent1Proxy.get_attr('running')

    Agent1PubAddress = Agent1Proxy.addr('PUBStream')
    Agent2Proxy.connect(Agent1PubAddress, handler = {'Intro': log_message})

    # Other stuff happens here with agent "prepping" -- in my code, it is contacting a DB and gathering info
    ################
    time.sleep(3)

    # Tell Agent 1 that Agent 2 is ready
    Agent2Proxy.each(3, Agent2Proxy.send('PUBStream', '2', topic = 'ImReady'))
    print('Im Ready message sent!')
```

---
Agent3.py
---
```
from osbrain import run_agent
from osbrain import run_nameserver
import osbrain
from osbrain.proxy import NSProxy, locate_ns
import time

osbrain.config['TRANSPORT'] = 'tcp'


def log_message(agent, message):
    agent.log_info('Received: %s' % message)


if __name__ == '__main__':
    # Get nameserver proxy
    ns = '127.0.0.1:1124'
    nsaddr = locate_ns(ns)
    nsP = NSProxy(nsaddr)

    # Run the Agent
    print('Registering Agent 3 with the server...')
    Agent3Proxy = run_agent('Agent3', nsaddr)
    print('Agent registered!')

    # Create proxy to Agent 1 and connect to receive Intro message
    Agent1Proxy = nsP.proxy('Agent1')
    Agent1PubAddress = Agent1Proxy.addr('PUBStream')
    Agent3Proxy.connect(Agent1PubAddress, handler={'Intro': log_message})

    # Other stuff happens here with agent "prepping" -- in my code, it is contacting a DB and gathering info
    ################
    time.sleep(3)

    # Tell Agent 1 that Agent 3 is ready
    Agent3Proxy.each(3, Agent3Proxy.send('PUBStream', '3', topic='ImReady'))
    print('Im Ready message sent!')
```

**Comment by Peque** [comment]
@sjanko2 A couple of comments:

Remember, read [the name server documentation](https://osbrain.readthedocs.io/en/stable/introduction.html#the-name-server) and:

```python
# Do not use this
osbrain.nameserver.NameServer.agents(ns_proxy)
# But rather
ns_proxy.agents()
```
Also (not documented, but [opened an issue for adding this](https://github.com/opensistemas-hub/osbrain/issues/169), thanks :+1:):

```python
# Instead of
nsaddr = locate_ns('127.0.0.1:1234')
nsP = NSProxy(nsaddr)
# You can simply do
nsP = NSProxy('127.0.0.1:1234')
```

You can currently not do this:

```python
agent_proxy.attribute = set()
```
It is not documented, so [I just opened an issue](https://github.com/opensistemas-hub/osbrain/issues/168), thanks for reporting. :blush:

Use the `set_attr` method instead (it allows you to set multiple attributes at the same time):

```python
agent_proxy.set_attr(attribute0=value0, attribute1=value1, ...)
```
Alternatively, if your agent is complex, you might want to go with [OOP](https://osbrain.readthedocs.io/en/stable/considerations.html#oop):

```python
class AgentManager(Agent):
     def on_init(self):
          self.counter = set()
          self.size = 3
          self.bind('PUB', alias='main')

     def ready(self, name):
          self.attribute.add(value)
          if len(self.counter) < self.size:
              return
          self.send('main', 'Reached the desired count!')


agent_proxy = run_agent('alias', base=AgentManager)
# Note how we can set the `ready` method as handler using its name
agent_proxy.connect(other_address, handler='ready')
```

Note how, in this last example, I am not checking the moment when all agents are ready from the script (using proxies), but rather directly from the `AgentManager`, in the `ready` handler.

This is what I see at first sight. Try to play a bit and change your code to see if you can make it work with this tips. :wink:
