### ISSUE TITLE
Support for parallel test coverage

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#173]
The idea is to improve coverage reports that sum-up results from different platforms (i.e.: Windows branches, Python < 3.5 branches...). This way we could remove `if sys.version_info` from `.coveragerc`.

Can we do it with Codecov? If we cannot, check [Code Climate](https://docs.codeclimate.com/docs/setting-up-test-coverage?utm_source=up&utm_medium=email&utm_campaign=201706&__s=cxfq3cvop3k94ucncqfc) or other alternatives.

**Comment by Peque** [comment]
@ocaballeror Take a look at this once you are done with the initial Windows CI.

**Comment by Peque** [comment]
It should fix [this latest coverage regression](https://codecov.io/gh/opensistemas-hub/osbrain/compare/a0d96cce3e4d3f52a2980ec7d5cc99872f238810...f6482eca17451a70cb0b1d09f5fb2b8fb77aa04a) and also allow us to remove the platform-dependent excluded lines in `.coveragerc`.

**Comment by ocaballeror** [comment]
Looking into this. It seems codecov can do the job, but I have to add `pytest-cov` to appveyor first, and see if that works.
