### ISSUE TITLE
Closing connections

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#176]
It is not docummented (we should document it).

@Flood1993 should we add a method (i.e.: `agent.close(self, alias)`) to ease things for the end-user?

**Comment by Flood1993** [comment]
@Peque Yes, I think it is a good idea, since the way to do it now is far from trivial. I will try implementing it and rebasing with #177 since they are related, and I will ask for a review on that one when its ready, ok?

**Comment by Flood1993** [comment]
Implemented in #177
