### ISSUE TITLE
Some documentation docstrings are messed up

### ISSUE THREAD

**Issue by Flood1993** [opensistemas-hub/osbrain#179]
Some functions, despite being one liners which make it clear what they do when looking at the code, are missing a docstring. Others, simply have the `Parameters` and `Returns` field in their docstring (with no description of what it does).

When looking at the generated API, this might not look good:
![doc_missing](https://user-images.githubusercontent.com/8102496/28564178-7af0d172-7128-11e7-8b71-62955805fe0c.PNG)

Therefore I think we should document every single method/function regardless of its complexity. Also, for very simple functions such as `Agent.list_timers()`, I think we could get rid of the `Parameters` and `Returns` fields to save some space. What do you think @Peque ?

**Comment by Peque** [comment]
Yeah, maybe in some cases it is cleaner to just have a little description. Anyway, for now, I would not remove any already-added parameters/returns in the docstrings.

100% agree that we should make sure all docstrings have at least a one-liner description to avoid those ugly results in the generated documentation.

**Comment by ocaballeror** [comment]
OK, I've gone through the entire API filling in the missing docstrings. I will create a PR for review soon, but first I want to make a couple of comments.

1. I don't really understand the difference between `shutdown` and `kill`. I get the concept of what they are trying to do differently, but I don't exactly understand what they do differently in the context of this project. Can you enlighten me on this?

2. For  some reason, some methods/parameters/attributes that are not part of our classes appear in the docs without any documentation. I am assuming they belong to the superclasses we are inheriting from, so there is no way I can add  docstrings to those. Here are a couple of examples:
![selection_005](https://user-images.githubusercontent.com/20464046/35384919-1358ddf4-01c7-11e8-853f-3076e99acca4.png)
![selection_006](https://user-images.githubusercontent.com/20464046/35384920-13724e88-01c7-11e8-877a-5795547abbb6.png)

**Comment by Peque** [comment]
@ocaballeror Awesome. :blush:

1) The shutdown method is a clean method to shutdown a running agent. It will actually call `.kill()` too. It is a way to ensure the shutting down and the killing are performed safely from the main thread. The kill method is not expected to be safe and is meant for non-running agents or blocked agents.
2) Yeah, there is nothing we can do about that. We just want to make sure our docstrings are fine. :innocent:

**Comment by Peque** [comment]
@ocaballeror Maybe we could improve the shutdown/kill API to make it more clear (maybe leave just one method with a parameter or something like that). Feel free to add a new issue if you feel it is important. Although I do not think we will be including those changes in 0.6.0. :wink:

**Comment by ocaballeror** [comment]
@Peque it totally makes sense to have separate methods, in my opinion. I was just asking about the specific implementation that we used for these. It's all clear now 👍

**Comment by ocaballeror** [comment]
Fixed by #227
