### ISSUE TITLE
Travis builds ocasionally stalling

### ISSUE THREAD

**Issue by Flood1993** [opensistemas-hub/osbrain#182]
This problem could be not ours. Just in case, reference here any stalled builds. If the build is to be relaunched, upload the raw log file instead of linking the URL.

Add the new ones at the end.

https://travis-ci.org/opensistemas-hub/osbrain/jobs/257634628
[travis_stall_01.txt](https://github.com/opensistemas-hub/osbrain/files/1176201/travis_stall_01.txt)
[travis_stall_02.txt](https://github.com/opensistemas-hub/osbrain/files/1190528/travis_stall_02.txt)
[log.txt](https://github.com/opensistemas-hub/osbrain/files/1199970/log.txt)
[log2.txt](https://github.com/opensistemas-hub/osbrain/files/1199971/log2.txt)
[log3.txt](https://github.com/opensistemas-hub/osbrain/files/1199999/log3.txt)
[log4.txt](https://github.com/opensistemas-hub/osbrain/files/1200147/log4.txt)
[travis_stall_03.txt](https://github.com/opensistemas-hub/osbrain/files/1276916/travis_stall_03.txt)
[travis_stall_04.txt](https://github.com/opensistemas-hub/osbrain/files/1276962/travis_stall_04.txt)
https://travis-ci.org/opensistemas-hub/osbrain/jobs/277983732
https://travis-ci.org/opensistemas-hub/osbrain/jobs/283438775
https://travis-ci.org/opensistemas-hub/osbrain/jobs/286774257
https://travis-ci.org/Peque/osbrain/jobs/289552073
[log5.txt](https://github.com/opensistemas-hub/osbrain/files/1425196/log5.txt)
[log6.txt](https://github.com/opensistemas-hub/osbrain/files/1425197/log6.txt)

**Comment by Peque** [comment]
Moving this to 0.5.0 to see if we can solve it before next release.

**Comment by Peque** [comment]
Let us keep an eye on this to see if it stalls again after fixing #190.

**Comment by Flood1993** [comment]
Seems like I got another stall: https://travis-ci.org/Flood1993/osbrain/builds/271982282?utm_source=email&utm_medium=notification

**Comment by Peque** [comment]
I guess we should verify all tests to see if there are possible infinite loops (there probably are).

We could also have a look at #189.

**Comment by Peque** [comment]
Maybe this is related: https://github.com/pytest-dev/execnet/issues/43

**Comment by Peque** [comment]
Closing this as it seems most errors have been fixed. Stalling may still occur but at least we should be getting the test that failed.

**Comment by Peque** [comment]
For future reference... the way to get where the errors occur with Travis in case the log does not show them:

![screenshot from 2017-11-02 14-30-33](https://user-images.githubusercontent.com/526577/32328565-a7f1f7f4-bfda-11e7-9dfe-4ca12d219904.png)

Downside is many times tests fail due to pytest/exexnet `INTERNALERROR`. So tests must be relaunched many times until the error is showed up.
