### ISSUE TITLE
ConnectionClosedError (teardown error) is back

### ISSUE THREAD

**Issue by Flood1993** [opensistemas-hub/osbrain#190]
Saw this error again here: https://travis-ci.org/Flood1993/osbrain/jobs/261780629

~~Will try uploading the raw log when I can, because right now Travis seems to be bugged and it won't let me. https://github.com/travis-ci/travis-ci/issues/8213~~

[log_ConnectionClosedError.txt](https://github.com/opensistemas-hub/osbrain/files/1205212/log_ConnectionClosedError.txt)

**Comment by Peque** [comment]
I'll try to have a look at it and see if we can reproduce it locally and fix it for next release. :sweat_smile:

**Comment by Peque** [comment]
Hopefully #182 is related to this. Wish those stalls were actual tracebacks... :stuck_out_tongue_winking_eye:
