### ISSUE TITLE
TimeoutError: Could not locate the name server!

### ISSUE THREAD

**Issue by aleixg** [opensistemas-hub/osbrain#191]
Hi guys,

I need some help here... :(

I have been trying to input the first of the codes shown in [https://osbrain.readthedocs.io/en/stable/introduction.html](url)

```
from osbrain import run_nameserver
from osbrain import run_agent
if __name__ == '__main__':
    # System deployment
    run_nameserver()
    agent = run_agent('Example')
    # Log a message
    agent.log_info('Hello world!')
```

I've also tried to try with the following code, 

```
from osbrain.nameserver impor random_nameserver_process
from osbrain.proxy import NSProxy
addr = random_nameserver_process(timeout=10).addr
ns = NSProxy(addr)
ns.shutdown()
```

On both of the attempts, spyder keeps on poping the following error:

**TimeoutError: Could not locate the name server!**

Environment:
- OS: Windows 7 Enterprise.
- osBrain version 0.4.4.

Is there anyone who could help me? Many thanks in advance guys!

**Comment by Flood1993** [comment]
Hello, @aleixg . I have updated your message to include the information about your environment you sent me. Did you get a chance to try to reproduce it on another computer? It would be great if you could try under the exact same environment.

**Comment by aleixg** [comment]
Hey @Flood1993! Thanks for the heads up, not yet.

I tried with the same environment but with another wifi (in order to check if there was something related to firewall or network issues) but it kept me showing the same error.

This afternoon I will try with another completely different environment and I will keep you posted about it, hope it works! 

Thanks!!

**Comment by aleixg** [comment]
Hey guys, 

I tried with Windows 10 Home edition, osBrain 0.4.4 version. 

:'''(

**Comment by Flood1993** [comment]
That's unfortunate... Did you get the same TimeOutError? Was it running on a virtual machine or in a different PC? Are you installing via ``pip``?

**Comment by aleixg** [comment]
Yeap :(  absolutely same error... Nope, different PC completely, different network. 

I did `pip install osbrain` from the Anaconda Prompt. Is that correct? I also updated on both attempts updating Spyder and Anaconda...

**Comment by Flood1993** [comment]
I guess it shouldn't matter. Normally what I do for installing on a new computer is install [Miniconda](https://conda.io/miniconda.html), and then from a command prompt create a new environment with ``conda create --name osbrain python=3``. Then activate that environment with ``activate osbrain`` and finally install osBrain: ``pip install osbrain``.

What Python version are you using when getting the error? Also, could you try running the script from a command prompt directly? I'm not sure what the issue might be, though...

**Comment by aleixg** [comment]
Ok @Flood1993 I did the following,

![image](https://user-images.githubusercontent.com/30875512/29206210-261d833c-7e81-11e7-82fe-8fcb453e2bcc.png)

Then, got the same error,

![image](https://user-images.githubusercontent.com/30875512/29206257-698b8b00-7e81-11e7-9946-29e7ada36f10.png)

For the packages version I am using,

Python 3.6.2
Conda 4.3.24

Is it correct what I am doing?

**Comment by Flood1993** [comment]
Yes, it seems right. As a desperate attempt, could you try opening the Python interpreter in the Anaconda Prompt  and try to run the code there?

**Comment by aleixg** [comment]
Thanks for your help @Flood1993!! Could you please guide me through? I mean, what I have to input is:

```
conda create --name osbrain python=3
activate osbrain
pip install osbrain
```

in the IPyhton console in Spyder?

**Comment by Flood1993** [comment]
No problem, hopefully we can solve this 😄 Please follow this steps:
- Press ``Windows Key + R`` on your keyboard.
- A window will come up. Type ``cmd`` in the text field and hit Enter. This will open a command prompt.
- In the command prompt, type ``activate osbrain``.
- Save the code snippet in a file, i.e.: ``example.py`` (make sure the file and the command prompt are in the same directory, for example, your desktop).
- Run the code with ``python example.py``.

Probably it will crash, too, but just to check...

**Comment by aleixg** [comment]
:( 
![image](https://user-images.githubusercontent.com/30875512/29207932-468fbcdc-7e88-11e7-8c2d-dd0e347ee75f.png)

**Comment by Flood1993** [comment]
Seems like the Anaconda installation wasn't added to your PATH. I have just checked and by default the option seems to be not checked during installation. No problem though, could you try the same steps but from the Anaconda Prompt?

**Comment by aleixg** [comment]
CANTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
BELIEVEEEEEEEEEEEEEEEEEEEEEEE
IT. :heart: 

W
O
R
K
E
D
!
!
!

You made my day @Flood1993!! Thank you very much, but the question is how can I now run the code and work with Spyder without doing all this?

Thank you very much!!

**Comment by Flood1993** [comment]
No problem, glad it worked! ^^ This means the problem is related to Spyder, somehow, and that would be a different issue... Last time I worked with Spyder was years ago and I don't have much experience with it, so I'm not exactly sure what can be the problem... Maybe Spyder isn't handling the installation correctly for some reason.

I will create a new issue referencing this one about things not working OK on Spyder. I will leave this one open in case you want to add something more!
