### ISSUE TITLE
Test SIGINTs

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#20]
Create tests to verify behavior on interruption signals. In example, an interrupted system should end up with all agents and name server killed (no Python process should linger).

See 7cb8c6fd108b279d882143d646f52913d3c95ef8 (revert) for an example of how agents can remain alive after SIGINT.

**Comment by Flood1993** [comment]
Are these correct?
- When sending a SIGINT to the NameServer agent, we want to take down the whole system.
- When sending a SIGINT to any other agent, we want to remote that agent from the system, but let every other thing untouched.

**Comment by Peque** [comment]
@Flood1993 Yes, that is correct. For now, however, I would suggest you to concentrate just on the first one, which is the most common case (i.e.: manually interrupting with <kbd>CTRL</kbd>+<kbd>C</kbd>).

**Comment by Peque** [comment]
I think 3 tests could be implemented here:

1. SIGINT an agent should kill it (implemented).
1. SIGINT a name server should kill all agents registered and the name server itself.
1. There should be a test that fails when reverting 7cb8c6fd108b279d882143d646f52913d3c95ef8 to check that no process is ever left alive after SIGINT.

We could then open a new ticket to implement other kind of interruption, if that makes sense... I have thought about 2-step interruption. First SIGINT captured results in clean exit/kill (i.e.: agent waits for code execution and tear-down and name server waits for all agents to be unregistererd). If another SIGINT is captured, kill with no mercy (as we are doing it right now). What do you think?

**Comment by Flood1993** [comment]
I think this is a good idea. I have implemented more tests related to this in #59 .

Perhaps this issue could be closed and we could open a new one about the 2-step interruption?

**Comment by Peque** [comment]
@Flood1993 Sure. Go ahead. :blush:
