### ISSUE TITLE
Document agent attributes

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#200]
`name`, `uuid`, ...

Any common/default agent attribute.

Maybe simply expand/complete https://osbrain.readthedocs.io/en/stable/api/agent.html.

What about #205?

**Comment by ocaballeror** [comment]
About to start working on this.

About the other issue you referenced, I don't think it's necessary, but if we are going to do this, we might as well document the private attributes as  well. It makes it easier for anyone looking to contribute to the project.

**Comment by Peque** [comment]
@ocaballeror Great. I think we can finish this first. Then we take on #200 (and #225, which is similar).

**Comment by ocaballeror** [comment]
Closed by #232
