### ISSUE TITLE
How to access all logged messages of an agent?

### ISSUE THREAD

**Issue by jonas912** [opensistemas-hub/osbrain#201]
Hello,

as said in the title, I'd like to **access all messages received and logged by an agent** to get an overview about its content. By now, I tried to save an incoming message inside the log handler with the following code:
```
def log(agent,message): 
    agent.log_info("Message'%s' from %s received." %(message[1],message[0]))
    global saved_message
    saved_message=(message[0],message[1])
```
My message is a tuple containing its sender on index 0 and the content itself on index 1.

In the main function, I try to access the tuple `saved_message`  by a simple `print` command which gives me the **error** _saved_message is not defined_ back.

Is the **handler-function** not capable of **using global variables**? Is there any **other osbrain-function** which could solve my problem?

Thank you

**Comment by Peque** [comment]
@jonas912 Can you share a [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve)? Try to always include this in your issues for us to better understand your problem and see if you are doing something wrong.

> Is the handler-function not capable of using global variables? Is there any other osbrain-function which could solve my problem?

The whole idea of a multi-agent system is to prevent shared memory between agents. If you want to share state then use message passing or use a proxy (which uses message passing under the hood).

Agents are (by default) system processes, which are independent from each other. It makes no sense to try to edit a global variable from one agent (one process) and read it from main (another process), and it will not work. :wink:

**Comment by jonas912** [comment]
@Peque I wrote a simple example to define my exact problem:
```
import osbrain

def log(agent,message): 
    agent.log_info("Received Message: %s" %message)
    i=i+1
    print(i)
    
if __name__=='__main__':
    ns=osbrain.run_nameserver()
    agent_a=osbrain.run_agent('agent_a')
    agent_b=osbrain.run_agent('agent_b')
    agent_c=osbrain.run_agent('agent_c')
    
    agent_a.set_method(save)
    
    addr=agent_b.bind('PUSH')
    agent_a.connect(addr,handler=log)
    agent_b.send(addr,'Hello from agent_b.')
    
    addr=agent_c.bind('PUSH')
    agent_a.connect(addr,handler=log)
    agent_c.send(addr,'Hello from agent_c.')    

    ns.shutdown()
```

To bring it down to an easy level, I only set an index variable` i` which should be increased by 1 for every execution of `log`. To get information about how many messages arrived, the actual value of `i` is to be put out by the function.
When running this program, i get the error _"Agent must be running to safely execute methods!"_ which I don't understand. Isn't `agent_a` the whole time running after calling the `run_agent` function? Please help.

**Comment by Peque** [comment]
@jonas912 Yeah, understanding remote tracebacks is harder than local tracebacks.

First, I think you mean `set_method(log)` instead of `set_method(save)`, right?

If you look at the top of the traceback it says: `local variable 'i' referenced before assignment`. You say `i = i + 1` but `i` is not declared.

You might want to use attributes in the agent. Please **read this two sections of the documentation carefully**:

- [OOP in osBrain](https://osbrain.readthedocs.io/en/stable/considerations.html#oop)
- [Setting initial attributes in agents](https://osbrain.readthedocs.io/en/stable/considerations.html#setting-initial-attributes)

If you don't like OOP:

```python
def log(agent, message):
    agent.i += 1
        print(self.i)


if __name__ == '__main__':
    # [...]
    agent_a.set_attr(i=0)
    agent_a.set_method(log)
    # [...]
```

If you like it:

```python
class MyAgent(osbrain.Agent):
    def on_init(self):
        self.i = 0

    def log(self, message):
        self.i += 1
        print(self.i)


if __name__ == '__main__':
    ns = osbrain.run_nameserver()
    agent_a=osbrain.run_agent('agent_a', base=MyAgent)
    agent_b=osbrain.run_agent('agent_b')
    agent_c=osbrain.run_agent('agent_c')

    addr=agent_b.bind('PUSH')
    agent_a.connect(addr, handler='log')
    agent_b.send(addr, 'Hello from agent_b.')

    addr=agent_c.bind('PUSH')
    agent_a.connect(addr, handler='log')
    agent_c.send(addr, 'Hello from agent_c.')

    ns.shutdown()
```

**Comment by jonas912** [comment]
@Peque By mistake I forgot to delete `set_method(save)`. It isn't part of the example and I already knew that it shouldn't be there, but thanks anyway for notifying me 👍 

As I wrote yesterday, I finally solved my problem by using the `set_method()` function in `agent_a` and running the method. Thanks to your fast and exact help, I can go on with my work.
