### ISSUE TITLE
Add test to check we do not leave IPC sockets open

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#216]
Shutting down or killing an agent should always result in all sockets being closed (and their corresponding files being deleted).

There is no test currently for that, but we should create one. I think it can be reproduced if we remove the `close_all()` call in shutdown/kill.

In example: bind a socket to an unique address. Check the socket file is created. Crash the agent, shutdown the agent, kill the agent, block the agent... Shutdown the name server, shutdown the agent, kill the agent... All cases should result in the socket begin closed and the socket file being deleted.

**Comment by ocaballeror** [comment]
How should I approach this? Should I create a single test for this, or multiple ones with different approaches (killing the agent, shutting it down, stopping the nameserver etc)?

Also, in the event that in one of those scenarios we don't actually close the IPC socket, am I supposed to fix it or should I create a separate issue for that?

**Comment by Peque** [comment]
@ocaballeror Always start with multiple ones. If you find out they share a lot of code, convert them to parametric tests (with `pytest.mark.parametrize`). Unless that means adding if-else clauses in the parametric test.

If you find out any of the tested scenarios fails... then we will see. :stuck_out_tongue_winking_eye:

**Comment by ocaballeror** [comment]
Ok, I've written most of the tests now, and I can confirm that the sockets are not being closed when either the agent or the name server crash. What now? Is it OK to create a PR when you know the tests are going to fail?

**Comment by ocaballeror** [comment]
Side note: what do you mean by "blocking the agent"? All I can think of is having an agent wait for a message in a REQ-REP channel, but that's not a scenario where we want to close the socket, is it?

**Comment by Peque** [comment]
@ocaballeror Definitely, create a PR for that, even if it fails. Yeah, blocking could be sending one message (you can do that with PUSH-PULL too). That is an scenario were we could be wanting to close the socket as well (i.e.: the agent is blocked, but we want to shutdown anyway --> the system should shutdown just fine and every socket closed).

**Comment by ocaballeror** [comment]
Apparently agents don't actually shut down until they receive the message they are waiting for. So if one agent is blocked in  a `recv` call, when `shutdown` is invoked it will be blocked  as well until the message is received. 

If `kill` is used instead, the socket will be closed but no exception will be raised, so `recv` will get stuck waiting forever. Maybe this should be another issue...
