### ISSUE TITLE
Allow running agents without alias

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#223]
If an alias is missing, maybe a random alias should be generated.

**Comment by ocaballeror** [comment]
Maybe, instead of an alias  we could use some combination of its parameters to create an auto-generated name.

I'm thinking, since the address has to unique, we could form a name like `agent_<address>` or something of the sort.

**Comment by ocaballeror** [comment]
Maybe, instead of a completely random alias, we could use some combination of its parameters to create an auto-generated name.

I'm thinking, since the address has to unique, we could form a name like agent_<address> or something of the sort.

**Comment by Peque** [comment]
@ocaballeror When you say address, to which address are you referring to? The Pyro4 server address?

**Comment by ocaballeror** [comment]
@Peque no. I was referring to the host and port attributes that `AgentProcess`es have. Are they not unique?

**Comment by Peque** [comment]
@ocaballeror Yeah those are used to create the Pyro4 server for each agent.

It is a good idea, but I am not sure it is 100% correct. I wonder:

- If we have 2 machines and we launch to agents bound to the localhost (i.e.: 127.0.0.1), they could both have the same address/port.
- The question is: can two agents bound to the same interface in different machines register in the same name server? Or does the name server need to share the network interface with all agents registered?
- If they could both register then that is not the best idea maybe.

On the other hand there is something risky about using that as the default alias. At some point one user might rely on that fact. If we ever change it we will [break someone's workflow](https://xkcd.com/1172/).

What you don't like about it being random? The fact that is not easily readable/recalled? If that is the case we could use [codenamize](https://github.com/jjmontesl/codenamize) or something similar.

**Comment by ocaballeror** [comment]
I didn't think about that scenario, but yeah, there would definitely be a conflict there.

Also, yes, I don't like completely random strings as names. Maybe I'm being a bit obsessive here, but I prefer more readable aliases. In a way they look more "friendly" to me.

I can deal with random strings, though, but I would prefer if we used codenamize or something of the sort.

**Comment by Peque** [comment]
@ocaballeror Fine with me. If we use codenamize I think we should:

- Generate a random UUID string.
- Generate a "short" codenamize alias (i.e.: 2 adjectives, max 5 characters each).
- Combine both to avoid collisions: adj0-adj1-noun-UUID

Then we could create a new issue to allow creating proxies to agents from the name server using just the beginning of the alias (i.e.: adj0-adj1-noun should be enough as long as there is no collision).

What do you think?

**Comment by ocaballeror** [comment]
A few things:
* I'm just seeing right now that agents already have a `uuid` attribute. Is it OK to use that one for the name or should we generate a new one?
* It appears codenamize always generates the same name for the same string of characters, so if we use a globally unique identifier, we can be sure the codenamized alias will be unique as well. If this is the case, maybe we can use that as a name, without appending the uuid to it. So adj0-adj1-noun would be enough.
* Are two adjectives even necessary? That looks like a very long name in my opinion.

**Comment by Peque** [comment]
- Yeah, we could use the `uuid` attribute, that would make a lot of sense.
- Yeah, that is called a hash or verification sum. Generated hashes are always identical for the same input (i.e.: it is a deterministic process), but there can be collisions (i.e.: two different inputs generating the same output), so we cannot be sure codenamized alias will be unique as well. :wink: With codenamize, using 2 adjectives and no max characters limit, there are 1899320400 possible combinations (which is also the chance of collision). With UUID, if I am not mistaken, you get a 128-bit random number, which results in 340282366920938463463374607431768211456 possible combinations. Probably, UUID collisions will never occur during osBrain's life. But I would not bet my life for it if we used only codenamize's more limited combinations.
- We could definitely reduce it, yeah, as long as we append the UUID there is no problem.

**Comment by ocaballeror** [comment]
Deleted my last comment by accident 😯. Pasting it here for history purposes:
> A few things:
> * I'm just seeing right now that agents already have a uuid attribute. Is it OK to use that one for the name or should we generate a new one?
> * It appears codenamize always generates the same name for the same string of characters, so if we use a globally unique identifier, we can be sure the codenamized alias will be unique as well. If this is the case, maybe we can use that as a name, without appending the uuid to it. So adj0-adj1-noun would be enough.
> * Are two adjectives even necessary? That looks like a very long name in my opinion.

**Comment by ocaballeror** [comment]
If we cannot trust names to be unique and we need to append the UUID to them, then we cannot ask the name server to create proxies to them just based on the codenamized alias, since that could lead to collisions. If that is the case and  we are going to need the UUID to refer to the agent anyway, we might as well not add the codenamize feature at all, and just go straight to using the UUID as the full name.

What do you think?

**Comment by Peque** [comment]
I think we might want to go with the UUID for now. It is the simplest and fastest way.

**Comment by ocaballeror** [comment]
Yeah, I'm not going to worry too much more about this.

It's a shame, though. I liked having the funny names around the API 😞.

**Comment by Peque** [comment]
Hehehe. Me too. We might find out a way to integrate something like that in the future. :blush:
