### ISSUE TITLE
Improve name server coverage

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#233]
It seems the `except PyroError` in `async_shutdown_agents` is not tested.

![screenshot from 2018-02-02 14-27-56](https://user-images.githubusercontent.com/526577/35735527-76d47cb2-0825-11e8-8148-ab1333ba100c.png)

Some times this might not be reflected as those lines, depending on the execution, might be executed. Anyway a test for this would be great.

**Comment by ocaballeror** [comment]
Done.
Just one question: Should I post a PR already? Or should I wait until we are done with 0.6.0 to do it?

**Comment by Peque** [comment]
@ocaballeror Sure, open a PR. We might even merge it for 0.6.0. :blush:
