### ISSUE TITLE
Test coverage and code quality

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#24]
Have a look at:
- https://codecov.io/
- https://codeclimate.com/
- https://coveralls.io/
- https://scan.coverity.com/

Features, advantages, disadvantages...?

**Comment by RadW2020** [comment]
scan.coverity looks great!
It is 100% focused in open source and totally free
And the list of current projects is amazing You can find linux and ScummVM per example ;)

**Comment by Peque** [comment]
I ended up integrating the first three, to try them in the following months.

@RadW2020 I did not integrate scan.coverity, however. If you find the time and want to give it a try yourself (with a fork of this project, for example), please, report back your experience. I didn't manage to get it to automatically update scan.coverity project status on each commit/pull request only modifying `.travis.yml` file (I would not want to add other service-specific files to the project) and without having to add an authentication token to the project.

**Comment by Peque** [comment]
@RadW2020 Also, scan.coverity may be better suited for C/C++ projects. Maybe for Python project CodeClimate can do the trick. :confused:
