### ISSUE TITLE
Maybe rename `.configure()` method

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#243]
@ocaballeror We can discuss this tomorrow. :wink:

**Comment by ocaballeror** [comment]
Let's discuss it 😄 

What's wrong with it?

**Comment by Peque** [comment]
I was thinking `.configure()` is perhaps a too generic name. In example: some people might have already implemented a `.configure()` method in their agent classes.

We, for example, implement a `.configure()` method in several osMarkets agents.

I was thinking about changing this to `.configure_timers`, `.before_run` `.before_running`, `preconfigure`... Or any other that you propose.

What do you think?

**Comment by ocaballeror** [comment]
I like `before_run` or `before_running` better. It definitely sounds more explicative of what this method is supposed to do 👍
