### ISSUE TITLE
Release version 0.6.0

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#244]
- Bump version.
- Tag release.
- Upload to PyPI.

**Comment by ocaballeror** [comment]
I'd like to know what the necessary steps are in order to do this. Even if it's just for the joy of learning 😬

**Comment by Peque** [comment]
Sure. :blush:

- Bump version: means to change the package version in `osbrain.__init__.py` and make a commit with that change. You can see there are similar commits for older releases in the Git history.
- Tag release: we create an annotated tag for each release with the specific version number and a simple comment. See `tag -l -n`. As you can see, before 0.4.0 we did not have a strict policy to tag releases and tags are named after the commit they were attached to...
- To upload to PyPI you simply execute `python setup.py sdist upload`. In order to do that you need to already have registered the project in PyPI and provide the required pakcage owner credentials. Once this is done the new version is available to be installed with `pip`.

Once we include a changelog (hopefully for 0.7.0+) this process will probably change a little.

**Comment by ocaballeror** [comment]
@Peque it's nice to know. I feel a little bit wiser now 😁.
