### ISSUE TITLE
Bind with differt ip host

### ISSUE THREAD

**Issue by gvacca** [opensistemas-hub/osbrain#246]
HI,
i have found a problem when bind a socket whith a different IP host and transfert tcp. If in bind a socket whit an IP whitout oprt, it returns as address 'localhost'., but if bind with IP and port, it return correctly the address with my IP and port. I think that the problem is in the procedure _bind_socket of Agent class ( it lose the information about the host, it should be "addr = host + ':' + str(port)" and not "addr = self.host + ':' + str(port)"

Regards !

**Comment by Peque** [comment]
Thanks for reporting this issue. We will have a look at it and, if acknowledged, we will include a fix before releasing [0.6.0](https://github.com/opensistemas-hub/osbrain/milestones/0.6.0).

**Comment by Peque** [comment]
Confirmed. Hopefully fixed by #247. Can you try that patch and see if it fixes your problem?

**Comment by Peque** [comment]
@gvacca If you want to try the fix you can just:

    pip install --upgrade git+git://github.com/Peque/osbrain.git@bindhost

**Comment by gvacca** [comment]
@Peque , ok, upgraded and work fine !
