### ISSUE TITLE
test_linger[2-1-True]

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#250]
- https://travis-ci.org/opensistemas-hub/osbrain/jobs/341786321
- https://travis-ci.org/opensistemas-hub/osbrain/jobs/341672572
- https://travis-ci.org/Peque/osbrain/jobs/341815179
- https://travis-ci.org/Peque/osbrain/jobs/342288465

**Comment by ocaballeror** [comment]
I had to expand the timeout for these tests because they were more frequently failing on Windows. Let's see if that helps, I'll check back on this when the windows compatibility PR is merged.

**Comment by Peque** [comment]
Closing in favor of #252.

**Comment by Peque** [comment]
Reopening: https://travis-ci.org/opensistemas-hub/osbrain/jobs/347174040
