### ISSUE TITLE
Windows tests seem to fail more often

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#259]
Test | Line
--- | ---
[`test_agent_loopback_header_unknown`](https://ci.appveyor.com/project/osbrain-ci/osbrain/build/job/63au4xrqvxni08jk) | osbrain\tests\common.py:35:
[`test_async_rep_send_handler_types[<lambda>-False]`](https://ci.appveyor.com/project/osbrain-ci/osbrain/build/1.0.8/job/93pvxghvv9945qpp) | osbrain\tests\common.py:35:
[`test_log_levels`](https://ci.appveyor.com/project/osbrain-ci/osbrain/build/1.0.9/job/o87p70i27n2uwknk) | osbrain\tests\common.py:35:
[`test_nameserver_proxy_shutdown_lazy_agents[True-5]`](https://ci.appveyor.com/project/osbrain-ci/osbrain/build/1.0.9/job/o87p70i27n2uwknk) | osbrain\tests\test_nameserver.py:155:
[`test_pubsub_topics_raw[raw]`](https://ci.appveyor.com/project/osbrain-ci/osbrain/build/1.0.9/job/byg0wi8cutaoe3v4) | osbrain\tests\common.py:35:
[`test_pubsub_topics_separator[cloudpickle]`](https://ci.appveyor.com/project/ocaballeror/osbrain-5qldx/build/1.0.1/job/xusdm84lmqsw19yl) | osbrain\tests\common.py:35:
[`test_pubsub_topics_separator[cloudpickle]`](https://ci.appveyor.com/project/osbrain-ci/osbrain/build/1.0.8/job/93pvxghvv9945qpp) | osbrain\tests\common.py:35:
[`test_pubsub_topics_separator[json]`](https://ci.appveyor.com/project/osbrain-ci/osbrain/build/1.0.9/job/o87p70i27n2uwknk) | osbrain\tests\common.py:35:
[`test_pubsub_topics_separator[pickle]`](https://ci.appveyor.com/project/osbrain-ci/osbrain/build/1.0.8/job/05t52l0fccmxs9mg) | osbrain\tests\common.py:35:
[`test_pushpull[json-Hello world]`](https://ci.appveyor.com/project/osbrain-ci/osbrain/build/1.0.3/job/fqbkoglohcpmi5bl) | osbrain\tests\common.py:35:
[`test_sync_pub_connect_handler_types[receive_method-False]`](https://ci.appveyor.com/project/ocaballeror/osbrain-5qldx/build/1.0.2/job/gnlwalrgavfvp558) | osbrain\tests\common.py:35:

Maybe setting the number of threads to 1 could help? Is it something different?

Add new occurrences of failures to the list above.

**Comment by ocaballeror** [comment]
Yes. I was just looking into this. I'm going to try and run the tests a few  more times with just one thread, and we'll see how that goes.

**Comment by Peque** [comment]
@ocaballeror We could also create here a table of tests failing and the reason they failed. Maybe we find a pattern that help us fixing the tests. The column N would be the number of occurrences (i.e.: if you find a repeated occurrence, simply increase that number).

**Comment by ocaballeror** [comment]
One thing I noticed in the latest builds, is that the tests only seem to fail at shutdown on python 3.4. I'll check the 3.5 changelog to see if there's anything that could affect us.

**Comment by Peque** [comment]
Yeah, you are right, it seems it is always in 3.4.

**Comment by ocaballeror** [comment]
I went through the entire changelog for 3.5 but didn't find anything that could be related to this. Let's hope #264 ends up fixing this, otherwise I have no idea what's going on :sweat_smile:
