### ISSUE TITLE
Flake8 ignores too many errors

### ISSUE THREAD

**Issue by ocaballeror** [opensistemas-hub/osbrain#283]
I'm assuming the expected behavior from this:
```yml
[flake8]
ignore =
    __init__.py E402 F401
```
Would be to ignore errors E402 and F401 only from `__init__.py`, but in fact, flake8 is ignoring those two errors globally.

We may be missing a couple of useful warnings, so we should probably investigate how to properly ignore them from just that file.

**Comment by ocaballeror** [comment]
As explained [here](https://gitlab.com/pycqa/flake8/issues/89#note_2208624), flake8 does not, and probably will not ever support per-file ignores.

The suggested solutions are to either add `# noqa` to every affected line (yikes!), or to install [this flake8 extension](https://github.com/snoack/flake8-per-file-ignores), which doesn't seem like a very bad idea imo.

**Comment by Peque** [comment]
Yeah, sorry for that, I just created a pull request... :sweat: 

I copied the syntax from when we used the old linting tools and, as it did not complained, I assumed it was working just fine.

PS: nice catch again! :blush:
