### ISSUE TITLE
Socket file removal tests randomly failing on Travis

### ISSUE THREAD

**Issue by ocaballeror** [opensistemas-hub/osbrain#287]
https://travis-ci.org/opensistemas-hub/osbrain/jobs/362494498
https://travis-ci.org/ocaballeror/osbrain/jobs/362021572
https://travis-ci.org/ocaballeror/osbrain/jobs/362012690

Occurrences
-----------------

Occurrences | Test
--- | ---
1 | `test_agent_close_ipc_socket_agent_blocked_nameserver_shutdown`
1 | `test_agent_close_ipc_socket_agent_crash_nameserver_shutdown`
3 | `test_agent_close_ipc_socket_agent_kill`

**Comment by Peque** [comment]
Yeah, I just found another one. Added a list to keep track of occurrence counts.

For now it seems the failure is always when the agent is killed or crashes (if the agent is blocked, then the name server will actually kill it, so it is the same).

**Comment by Peque** [comment]
@ocaballeror When were they last modified? We used to have that problem before d76a1ea88c615f45f2e1156684f02176a0a1d007.

Otherwise it might mean you can actually reproduce what we are seeing in Travis. :smile:

**Comment by ocaballeror** [comment]
I have a few ones from February 2-7, and the next ones were created on March 27th, so that could be a good clue of where to find a possible bug.

**Comment by ocaballeror** [comment]
I just realized I can get osbrain to keep the socket files by killing the nameserver process with `^C` before it has time to be shut down cleanly, which makes sense, but it's something we should address in #249 before it's merged.

That is probably the reason why I had so many leftover files in my system, and that also makes me think that the one socket file I supposedly got to keep on purpose by running the tests over and over was actually the result of a manually killed process. That's bad news, because it means I have not been able to reproduce the error locally, and that this issue will be a pain to debug :sweat:

**Comment by Peque** [comment]
I was able to reproduce it: #293

Working on a fix...
