### ISSUE TITLE
Too strict timeouts?

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#290]
https://travis-ci.org/opensistemas-hub/osbrain/jobs/362602555

Maybe increase from 0.1 to 0.2 or 0.3?

**Comment by ocaballeror** [comment]
Or more! After all, we know the logger will receive that message, so setting the timeout to .6, or 5 seconds makes no difference. We know it will happen eventually, so no need to force such a short timeout.

**Comment by Peque** [comment]
I do not agree. In the case of the `test_wait_timeout` (and maybe others as well) we are testing that the timeout is working as expected. In example: if we set 1 second timeout, we are expecting the agent to wait only 1 second.

Unfortunately this timeouts (and measuring them) are problematic with CI services, so we need to be more lenient. Still, in my opinion, we should try to be somewhat close to the expected timeout.

**Comment by ocaballeror** [comment]
I see what you mean. Can we settle on `.5` seconds for these tests? That should be enough to test that wait times are working fine, and also to never fail on any CI platform.

**Comment by Peque** [comment]
Yeah, `.5` should be more than enough.
