### ISSUE TITLE
Tests failing on travis

### ISSUE THREAD

**Issue by ocaballeror** [opensistemas-hub/osbrain#311]
https://travis-ci.org/opensistemas-hub/osbrain/jobs/427931967

It's a weird error, so it's probably a Travis thing. I also launched the test suite locally and everything works flawlessly.

Just opening an issue so we remember to investigate this if it keeps happening in the future.

***Edit***: [raw log](https://github.com/opensistemas-hub/osbrain/files/2378229/log_36.txt).

**Comment by Peque** [comment]
@ocaballeror Can you `rm -rf .tox && reset && tox -e py36`? Just to make sure Tox is not using any outdated package version.

I can reproduce the error. It seems downgrading `pytest` to 3.7.4 fixes this issue.

**Comment by Peque** [comment]
Opened an issue in: https://github.com/pytest-dev/pytest/issues/3973

**Comment by Peque** [comment]
This is no longer a problem, I think. Closing...
