### ISSUE TITLE
Is there a way to have multiple communication channels between agents?

### ISSUE THREAD

**Issue by choochipastol** [opensistemas-hub/osbrain#324]
Say I have a controller agent that is in control of ten battery agents. Can I have multiple communication channels, one for example when the controller needs to send out general instructions to all batteries, and others when it needs to send commands to individual batteries?

Or is only one channel possible and I have to include flags or names in commands being sent out to process on the other end?

Any help will be greatly appreciated.

**Comment by ocaballeror** [comment]
You can definitely have multiple connections in one agent. That is why we use aliases to specify who the agent should send the message to. You can `.bind(alias='')` as many times as you want, specifying different aliases, and then use `.send(alias='whatever')` to only send the message to that address.

In your case, I would use a PUB-SUB channel for the general instructions that all batteries need to receive, and individual PUSH-PULL (or any other, to be honest) connections from the controller to each of the nodes.

Consider this code as an example:
```python
import random
from osbrain import run_nameserver
from osbrain import run_agent

def log_main(agent, message):
    agent.log_info('MAIN: Received ' + message)

def log_direct_msg(agent, message):
    agent.log_info('DIRECT: Received ' + message)

if __name__ == '__main__':
    ns = run_nameserver()
    controller = run_agent('controller')
    main_addr = controller.bind('PUB', alias='main')
    batteries = []
    for i in range(10):
        battery = run_agent('battery%d' % i)
        battery.connect(main_addr, handler=log_main)
        addr = controller.bind('PUSH', alias='battery%d' % i)
        battery.connect(addr, handler=log_direct_msg)
        batteries.append(battery)

    controller.send('main', 'All batteries receive this')
    number = random.choice(range(10))
    controller.send('battery%d' % number, 'Hello battery #%d' % number)
    ns.shutdown()
```

**Comment by ocaballeror** [comment]
Also, if you are going to use a PUB-SUB pattern, I would recommend you read a bit on [topics](https://osbrain.readthedocs.io/en/stable/basic_patterns.html#filtering), they may come useful for a setup like this.

**Comment by choochipastol** [comment]
Thank you for replying so quickly, I'll try setting up multiple connections
with different aliases.

Thanks for this library too, you guys are amazing. Would have had to learn
Java for Jade if I hadn't found this library.

**Comment by ocaballeror** [comment]
All credit goes to @Peque :grin: 

Glad you like it!

**Comment by Peque** [comment]
All credit goes to [@contributors](https://github.com/opensistemas-hub/osbrain/graphs/contributors). :stuck_out_tongue_winking_eye: 

@choochipastol Closing this issue as resolved. Feel free to reopen if needed. Do not hesitate to contribute to the current documentation if you feel there is something missing/unclear.
