### ISSUE TITLE
osbrain passing object to agent 

### ISSUE THREAD

**Issue by osmmaz** [opensistemas-hub/osbrain#331]
how can i pass object or table to an agent in osbrain

**Comment by Peque** [comment]
Hi @osmmaz,

Would you mind to share more information about your problem? Have you gone through [the osBrain documentation](https://osbrain.readthedocs.io/en/stable/) first? Are you getting any exceptions with the code you currently have? Do you have a reproducible example?

You may find these resources useful:

- [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)
- [How to create a Minimal, Reproducible Example?](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Peque** [comment]
Closing as invalid until more information is provided. Feel free to reopen.
