### ISSUE TITLE
How to accept input within a handler function?

### ISSUE THREAD

**Issue by LimingXu-notts** [opensistemas-hub/osbrain#334]
I have read through the documentation, but could not to find a solution that could accept input in a handler function. I have two agents to connect using "SYNC_PUB", and when an agent receives message another agent, it can accept input (a dialogue to ask for input) and then send this message back to the other agent. 

I would like to create interfaces for the agents, could anyone tell me how to implement this? Any suggestions? Thanks a lot in advance.

**Comment by Peque** [comment]
I think you may be referring to this: https://github.com/opensistemas-hub/osbrain/issues/313

Feel free to reopen otherwise.
