### ISSUE TITLE
Keeping track of agent information

### ISSUE THREAD

**Issue by HeediBoy** [opensistemas-hub/osbrain#342]
Hi,

I am new to multi-agent systems. I am hoping I can get a response on the following:

I am trying to implement 4 agents where: Agent0 is the agent which the incoming data comes into and would basically act as a post office for data and send the data to Agent1 and Agent 2 which would then manipulate the data a bit more. Both of which would, finally, send their transformed data to Agent3. I need a way to keep track of what Agent1 and Agent2 has sent to Agent3. I am using a OOP approach for this so I have 4 classes for each of the agents. Could I please get some help?

**Comment by Peque** [comment]
@HeediBoy That looks too wide for an answer, sorry. :sweat_smile: 

Please, have a look at the [osBrain documentation](https://osbrain.readthedocs.io/), where you should be able to learn the basics to implement a solution for your problem:

- How to setup your system
- Which communication patterns to use.

Do not hesitate to open future issues if you find any while using the library, but make sure they are more concrete and share the code you have to reproduce them.

**Comment by HeediBoy** [comment]
Thanks for the feedback
