### ISSUE TITLE
Doubts for using other external modules on Agents

### ISSUE THREAD

**Issue by tfspire** [opensistemas-hub/osbrain#352]
Hi,

I'm a beginner on python so I have some doubts how should I use osbrain.

I want for example to have an agent that the only thing that he do is to be waiting for messages from a specific telegram channel using the Telethon module.

I know that I can set up new classes and passing them to the agents, but how can I pass the imports? Because I would need to import on the agents the Telethon module in order to use it.

Or do I need to modify the agent.py to work for my use case?

Thanks

**Comment by Peque** [comment]
Hi,

I would suggest you to carefully read through the [osBrain documentation](https://osbrain.readthedocs.io/) to understand how to work with it. Read at least the first 5 sections (from "About osBrain" until "Timers").

You do not need to modify `agent.py` to use external modules on agents.

For your use case:

- You probably want to start with a timer to check the Telegram channel periodically
- Alternatively, you may want to have a look at [how to execute one-way calls](https://osbrain.readthedocs.io/en/stable/advanced_proxy_handling.html) to continuously read from the Telegram channel and generate events in the agent through the internal `inproc://loopback` socket
- You can always replace the agent's `loop()` method with yours, but then you would lose the ability to communicate with that agent as you would normally with other agents in the network.

Good luck with your project! :blush:

**Comment by tfspire** [comment]
Hi,

Thank you so much for your reply. 
I will read better because I checked before and didn't find how to use the external modules.

Regarding telegram, I already using telethon module that generates events when a new message is received, so I will just adapt the stuff that I already have to use with osbrain (it looks awesome!! )

Regard :)
