### ISSUE TITLE
Configurable serialization

### ISSUE THREAD

**Issue by Flood1993** [opensistemas-hub/osbrain#36]
As of now, the default method for communication between agents is through pickle serialization. This makes feeding data through outside Python a difficult task. Use of picke should be optional. Add raw message passing?

**Comment by Peque** [comment]
This should be configurable through global/environment variable, per-agent and per-socket as well.

Options: `pickle` (default), `raw`/`none`.

**Comment by Peque** [comment]
JSON, MessagePack, ...?
