### ISSUE TITLE
Docs: Serialization

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#46]
Documentation on serialization should include instructions on how to change the serialization method (i.e.: global setting, per-agent configuration and per-socket configuration).

Ideally, an example should be added to the `examples` folder.

There should be a subsection in this documentation page to warn about differences in PUB-SUB when using raw sockets (i.e.: topic is not separated from the message, the user must take care of that...). It just makes sense to have a "raw" ZeroMQ behavior when using the `raw` serialization.

**Comment by Flood1993** [comment]
I think we could close this issue. I'm not sure if the simple examples that I uploaded are good enough (code is assumed to be in some context, the files will not run by themselves). I can change them without a problem, I just wasn't sure whether the extra space for the documentation is worth it.

**Comment by Flood1993** [comment]
Well, the CI system has made me turn them into real Python code :D.
