### ISSUE TITLE
Lingering in PUSH-PULL patterns

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#84]
Related to #83.

Add an option to set `linger` in PUSH sockets.

**Comment by Peque** [comment]
This was merged in #96.

@Flood1993 Should we consider setting a default value greater than 0? I was thinking about this and actually, this only comes into play when shutting down (closing agents), so for normal communications we will not break any ZMQ good practices, but when shutting down we may avoid some nasty blocking issues...

**Comment by Flood1993** [comment]
You are right, since it is only important on shutdown, it would make sense to have a default timeout. What would be an appropiate value?

**Comment by Peque** [comment]
@Flood1993 I'd say a value that does not annoy the user too much while waiting... 1 second? Maybe even less. :thinking:
