### ISSUE TITLE
Configurable HWM

### ISSUE THREAD

**Issue by Peque** [opensistemas-hub/osbrain#87]
Optionally configure HWM behavior (crash vs. wait/drop).

Analyze PUSH-PULL behavior when HWM reached and linger is set.

**Comment by Flood1993** [comment]
I will be updating this comment with my findings.

It seems that the default ZMQ behaviour in the push/pull pattern when the HWM is full on the receiving end, is to simply ignore the new messages.

**Comment by Peque** [comment]
See #97.
